### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by W4RH4WK** [almarklein/timetagger_cli#14]
Sorry if this question is misplaced here.

Among Timetagger's features, it lists:

> TimeTagger gives you the same smooth time-tracking experience on any device, no matter the screen size. It can be used off-line, and your data gets automatically synced.

I assume this refers to the web-client which operates from cache / browser local storage and just syncs with the server once a connection is re-established, right?

The CLI does not support any way of storing time tracking locally when offline, and syncing it back with the server at a later point, or does it?

**Comment by almarklein** [comment]
This is the correct place for a question like this.

That feature indeed applies to the web app. A CLI client could implement that, but I prefer this one to be lean, so it does not have a cache.
